In [1]:
# Algoritmo de visualização de dados
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Bibliotecas para manipulação e análise de dados
import numpy as np

# Algoritmos de Normalização e Padronização dos dados
from sklearn.preprocessing import StandardScaler

# Algoritmo de Kmeans
from sklearn.cluster import KMeans

In [2]:

idade = [20, 27, 37, 52]
salario = [1000, 1200, 3000, 4000]
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])
display(base_salario) 

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [3]:
# Para evitar que o algoritmo classifique errado pelo atributo salario ser maior iremos padronizar os dados

scaler = StandardScaler()
base_salario = scaler.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [4]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(base_salario)

KMeans(n_clusters=3)

In [5]:
centroides = kmeans.cluster_centers_
display(centroides)

display(f"\n esses são os centroides:")
scaler.inverse_transform(kmeans.cluster_centers_)


array([[ 0.94906354, -0.73145432],
       [ 0.07703438,  1.11413572],
       [-1.301881  , -0.75688568]])

'\n esses são os centroides:'

array([[  50.6       , 1790.        ],
       [  41.16666667, 5600.        ],
       [  26.25      , 1737.5       ]])

In [6]:
# Retorna o grupo em que cada um dos registros pertence 
rotulos = kmeans.labels_
rotulos

array([2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [11]:
# Cria um gráfico de dispersão para os dados de salário
grafico = px.scatter(x = base_salario[:, 0], y = base_salario[:, 1], color=rotulos)  

# Cria um gráfico de dispersão para os centroides dos grupos
grafico2 = px.scatter(x = centroides[:, 0], y = centroides[:, 1], size=[12,12,12])  

# Combina os dados dos dois gráficos em uma única figura. Caso queira ver os dois separados, é possível
grafico3 = go.Figure(grafico.data + grafico2.data)  

grafico3